/**
 * Seed script — populates a development database with a realistic demo org,
 * user, projects, documents, brand voices, generations, and usage history.
 *
 * Run: npm run db:seed   (requires DATABASE_URL)
 * Safe to re-run: it upserts the org/user and clears their child rows first.
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const USER_ID = "seed-demo-user";
const USER_EMAIL = "demo@zinkpen.ai";

async function main() {
  const user = await prisma.user.upsert({
    where: { id: USER_ID },
    update: { email: USER_EMAIL, name: "Demo Operator" },
    create: { id: USER_ID, email: USER_EMAIL, name: "Demo Operator" },
  });

  // Find or create the demo org (and owner membership).
  let membership = await prisma.membership.findFirst({ where: { userId: user.id }, include: { org: true } });
  let orgId: string;
  if (membership) {
    orgId = membership.orgId;
  } else {
    const org = await prisma.organization.create({
      data: {
        name: "ZinkPen Demo Workspace",
        plan: "professional",
        members: { create: { userId: user.id, role: "owner" } },
      },
    });
    orgId = org.id;
    membership = await prisma.membership.findFirst({ where: { orgId, userId: user.id }, include: { org: true } });
  }

  // Reset child data for a clean, deterministic seed.
  await prisma.generation.deleteMany({ where: { orgId } });
  await prisma.usageRecord.deleteMany({ where: { orgId } });
  await prisma.document.deleteMany({ where: { project: { orgId } } });
  await prisma.project.deleteMany({ where: { orgId } });
  await prisma.brandVoice.deleteMany({ where: { orgId } });

  // Projects
  const projects = await Promise.all(
    [
      { name: "Q3 Demand Gen", description: "Top-of-funnel content engine", color: "#5b63f0" },
      { name: "GovCon Pipeline", description: "SBIR + capability statements", color: "#0F766E" },
      { name: "Executive Comms", description: "Board briefs & thought leadership", color: "#9333ea" },
      { name: "Brand Refresh", description: "Website + social relaunch", color: "#e3a833" },
    ].map((p) => prisma.project.create({ data: { orgId, ...p } })),
  );

  // Documents
  const docs = [
    { title: "The 2026 Content Operations Playbook", type: "Long-form Article", status: "in_review" as const, p: 0 },
    { title: "SBIR Phase I — Technical Narrative", type: "SBIR Proposal", status: "draft" as const, p: 1 },
    { title: "Q2 Board Brief", type: "Executive Brief", status: "final" as const, p: 2 },
    { title: "LinkedIn Carousel — Pricing Strategy", type: "Social / Visual", status: "final" as const, p: 0 },
    { title: "Capability Statement — Cyber Services", type: "Capability Statement", status: "in_review" as const, p: 1 },
    { title: "Homepage Hero Rewrite", type: "Website Copy", status: "draft" as const, p: 3 },
  ];
  for (const d of docs) {
    const content = `# ${d.title}\n\nDraft content for ${d.title}. Generated by ZinkPen and refined in the editor.`;
    await prisma.document.create({
      data: {
        title: d.title,
        type: d.type,
        status: d.status,
        content,
        words: content.split(/\s+/).length,
        projectId: projects[d.p].id,
        authorId: user.id,
        versions: { create: { content, label: "Seed draft" } },
      },
    });
  }

  // Brand voices
  await prisma.brandVoice.createMany({
    data: [
      { orgId, name: "Executive Authority", description: "Confident, concise, board-room ready.", traits: ["Authoritative", "Concise", "Data-driven"], sampleText: "We lead with outcomes and back every claim with evidence." },
      { orgId, name: "GovCon Compliance", description: "Precise, requirement-traceable, formal.", traits: ["Formal", "Precise", "Compliant"], sampleText: "Our approach maps directly to each requirement with full traceability." },
      { orgId, name: "Founder Voice", description: "Warm, direct, story-led.", traits: ["Warm", "Direct", "Story-led"], sampleText: "Here's what we learned the hard way, and what it means for you." },
    ],
  });

  // Usage + generations across the last 14 days
  const features = ["studio", "proposal", "humanizer", "visuals", "research", "grammar"];
  const usage: { orgId: string; kind: string; amount: number; feature: string; createdAt: Date }[] = [];
  const generations: { orgId: string; authorId: string; feature: string; prompt: string; output: string; provider: string; words: number; createdAt: Date }[] = [];
  for (let day = 13; day >= 0; day--) {
    const date = new Date();
    date.setDate(date.getDate() - day);
    const gensToday = 2 + Math.floor(Math.random() * 5);
    for (let i = 0; i < gensToday; i++) {
      const feature = features[Math.floor(Math.random() * features.length)];
      const words = 200 + Math.floor(Math.random() * 1200);
      usage.push({ orgId, kind: "words", amount: words, feature, createdAt: date });
      if (feature === "visuals") usage.push({ orgId, kind: "images", amount: 5, feature, createdAt: date });
      generations.push({
        orgId,
        authorId: user.id,
        feature,
        prompt: `Seed ${feature} prompt`,
        output: `Seed ${feature} output (${words} words).`,
        provider: "demo",
        words,
        createdAt: date,
      });
    }
  }
  await prisma.usageRecord.createMany({ data: usage });
  await prisma.generation.createMany({ data: generations });

  console.log(`✅ Seeded org ${orgId}: ${projects.length} projects, ${docs.length} docs, ${generations.length} generations, ${usage.length} usage records.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
